package edu.iastate.metnet.metaomgraph.test;

import edu.iastate.metnet.metaomgraph.utils.Utils;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Set;
import java.util.TreeMap;


public class PathAndLocusSmasher {
    static String[] allPaths = {"(deoxy)ribose phosphate metabolism",
            "13-LOX and 13-HPL pathway",
            "4-aminobutyrate degradation I",
            "<i>cis</i>-zeatin biosynthesis",
            "<i>de novo</i> biosynthesis of purine nucleotides",
            "<i>de novo</i> biosynthesis of purine nucleotides (v4.0)",
            "<i>trans</i>-zeatin biosynthesis",
            "ABA",
            "ABA biosynthesis",
            "abscisic acid biosynthesis",
            "abscisic acid glucose ester biosynthesis",
            "acetate utilization",
            "acetyl-CoA biosynthesis (from citrate)",
            "acetyl-CoA biosynthesis (from pyruvate)",
            "Acetyl-CoA Biotin network",
            "acrylonitrile degradation",
            "acyl-ACP desaturation pathway",
            "acyl-ACP desaturation pathway (v3.5)",
            "acyl-ACP thioesterase pathway",
            "acyl-CoA synthetase pathway",
            "acyl-CoA thioesterase pathway",
            "additionACL",
            "adenosylmethionine biosynthesis",
            "aerobic glycerol catabolism",
            "aerobic respiration",
            "aerobic respiration -- alternative oxidase pathway",
            "AGRIS regulatory network - full",
            "alanine biosynthesis",
            "alanine biosynthesis (v4.0)",
            "alanine biosynthesis II",
            "alanine degradation",
            "alanine degradation (v4.0)",
            "aldoxime degradation",
            "alpha-amyrin biosynthesis",
            "ammonia assimilation cycle",
            "anthocyanin biosynthesis (pelargonidin 3-O-glucoside, cyanidin 3-O-glucoside)",
            "APX1 signal transduction pathway",
            "arginine biosynthesis",
            "arginine biosynthesis 4",
            "arginine biosynthesis II (acetyl cycle)",
            "arginine biosynthesis III",
            "arginine degradation I",
            "arginine degradation II",
            "arginine degradation III",
            "ascorbate biosynthesis",
            "ascorbate biosynthesis (v4.0)",
            "ascorbate glutathione cycle",
            "Ascorbate Glutathione Pathway (cytosol, WYJ)",
            "Ascorbate glutathione pathway (mitochondria)",
            "Ascorbate glutathione pathway (plastid stroma)",
            "asparagine biosynthesis",
            "asparagine biosynthesis (v4.0)",
            "asparagine biosynthesis and degradation",
            "asparagine biosynthesis I",
            "asparagine degradation 1",
            "asparagine degradation I",
            "aspartate biosynthesis",
            "aspartate biosynthesis (v4.0)",
            "Autophagy",
            "Auxin signaling",
            "beta-alanine biosynthesis I",
            "beta-alanine biosynthesis II",
            "beta-alanine biosynthesis III",
            "biosynthesis of chlorophyll",
            "biosynthesis of proto- and siroheme",
            "biotin biosynthesis I",
            "biotin biosynthesis II",
            "branched-chain alpha-keto acid dehydrogenase complex",
            "Brassinolide biosynthesis (WYJ)",
            "brassinosteroid biosynthesis I",
            "brassinosteroid biosynthesis II",
            "brassinosteroid biosynthesis III",
            "brassinosteroids signaling",
            "C2 Photorespiration cycle (WYJ)",
            "CA1P biosynthesis",
            "Calvin cycle",
            "Calvin cycle (v4.0)",
            "Calvin Cycle (WYJ)",
            "camalexin biosynthesis",
            "cardiolipin biosynthesis",
            "carotenoid biosynthesis",
            "Catalase Ascorbate Glutathione pathway",
            "cellulose biosynthesis",
            "chlorophyll <i>a</i> degradation",
            "chlorophyll a biosynthesis I",
            "chlorophyll a biosynthesis II",
            "chlorophyll biosynthesis",
            "Chlorophyll Biosynthesis (WYJ)",
            "chlorophyll cycle",
            "cholesterol biosynthesis",
            "choline biosynthesis I",
            "choline biosynthesis II",
            "choline biosynthesis III",
            "chorismate biosynthesis",
            "citrulline biosynthesis",
            "citrulline degradation",
            "citrulline-nitric oxide cycle",
            "CMP-KDO biosynthesis I (from D-arabinose 5-phosphate)",
            "CMP-KDO biosynthesis II (from D-ribulose 5-phosphate)",
            "coenzyme A biosynthesis",
            "coniferin metabolism",
            "coumarin biosynthesis (via 2-coumarate)",
            "Cuticular wax",
            "cutin biosynthesis",
            "cyanate degradation",
            "cyanate degradation (v4.0)",
            "cyanide degradation",
            "cyclopropane and cyclopropene fatty acid biosynthesis",
            "cysteine biosynthesis",
            "cysteine biosynthesis (v4.0)",
            "cytokinins 7-<i>N</i>-glucoside biosynthesis",
            "cytokinins 9-<i>N</i>-glucoside biosynthesis",
            "cytokinins degradation",
            "cytokinins-<i>O</i>-glucoside biosynthesis",
            "D-arabinose catabolism",
            "de novo biosynthesis of pyrimidine deoxyribonucleotides",
            "de novo biosynthesis of pyrimidine ribonucleotides",
            "de novo biosynthesis of pyrimidine ribonucleotides (v4.0)",
            "dolichyl-diphosphooligosaccharide biosynthesis",
            "Drought regulation",
            "dTDP-L-rhamnose biosynthesis",
            "ent-kaurene biosynthesis",
            "epicuticular wax biosynthesis",
            "esculetin biosynthesis",
            "ethanol degradation",
            "ethylene biosynthesis and methionine cycle",
            "ethylene signaling",
            "fatty acid alpha-oxidation",
            "fatty acid beta-oxidation I (saturated)",
            "fatty acid beta-oxidation II (unsaturated, even number)",
            "fatty acid beta-oxidation III (unsaturated, odd number)",
            "fatty acid biosynthesis - initial steps",
            "fatty acid biosynthesis, initial steps",
            "fatty acid elongation in maize",
            "fatty acid elongation, saturated",
            "fatty acid elongation, unsaturated",
            "fatty acid omega-oxidation",
            "fatty acid synthesis: C16 to C18",
            "fatty acid synthesis: C2 to C4",
            "fatty acid synthesis: C4 to C16",
            "ferulate and sinapate biosynthesis",
            "Flavonoid (WYJ)",
            "flavonoid biosynthesis",
            "flavonol biosynthesis",
            "flavonol biosynthesis (v3.5)",
            "folate polyglutamylation I",
            "folate polyglutamylation II",
            "folate transformations",
            "formaldehyde oxidation IV (thiol-independent)",
            "formylTHF biosynthesis I",
            "free phenylpropanoid acid biosynthesis (v3.5)",
            "GA12 biosynthesis",
            "galactose degradation I",
            "galactose metabolism",
            "galactose, galactoside and glucose catabolism",
            "gamma-glutamyl cycle",
            "GDP-D-mannose biosynthesis",
            "GDP-L-fucose biosynthesis I (from GDP-D-mannose)",
            "GDP-L-fucose biosynthesis II (from L-fucose)",
            "GDP-L-galactose biosynthesis",
            "geranyldiphosphate biosynthesis",
            "geranylgeranyldiphosphate biosynthesis I (cytosolic)",
            "geranylgeranyldiphosphate biosynthesis II (plastidic)",
            "gibberellin acid signaling",
            "gibberellin biosynthesis I (non C-3, non C-13 hydroxylation)",
            "gibberellin biosynthesis II (early C-3 hydroxylation)",
            "gibberellin biosynthesis III (early C-13 hydroxylation)",
            "gibberellin inactivation",
            "gluconeogenesis",
            "glucose 1-phosphate metabolism",
            "glucosinolate biosynthesis from homomethionine",
            "glucosinolate biosynthesis from homomethionine (v3.5)",
            "glucosinolate biosynthesis from phenylalanine",
            "glucosinolate biosynthesis from phenylalanine (v3.5)",
            "glucosinolate biosynthesis from tryptophan",
            "glucosinolate biosynthesis from tryptophan (v3.5)",
            "glucosinolate breakdown",
            "glutamate biosynthesis I",
            "glutamate biosynthesis II",
            "glutamate degradation I",
            "glutamate degradation II",
            "glutamate degradation III",
            "glutamate degradation VII",
            "glutamine biosynthesis",
            "glutamine biosynthesis (v4.0)",
            "glutathione biosynthesis",
            "glutathione biosynthesis (v3.5)",
            "glutathione degradation",
            "glutathione redox reactions I",
            "glycerol degradation",
            "glycine biosynthesis",
            "glycine biosynthesis (v4.0)",
            "glycine degradation",
            "glycogen catabolism",
            "glycolate and glyoxylate degradation II",
            "glycolipid biosynthesis",
            "glycolipid desaturation",
            "glycolipid desaturation (v3.5)",
            "glycolysis I",
            "glycolysis II",
            "glycolysis II (plant plastids) (v4.0)",
            "Glycolysis-cytosol (WYJ)",
            "glyoxylate cycle",
            "Heat stress regulation",
            "heme biosynthesis",
            "heme biosynthesis (v4.0)",
            "histidine biosynthesis (v3.5)",
            "histidine biosynthesis I",
            "homocysteine and cysteine interconversion",
            "homogalacturonan degradation",
            "homomethionine biosynthesis",
            "homomethionine biosynthesis (v3.5)",
            "homoserine biosynthesis",
            "IAA biosynthesis I",
            "IAA biosynthesis II",
            "IAA conjugate biosynthesis",
            "inositol oxidation pathway",
            "isoleucine biosynthesis",
            "isoleucine biosynthesis (v4.0)",
            "isoleucine degradation",
            "isoleucine degradation (v4.0)",
            "isopentenyl diphosphate biosynthesis, mevalonate-independent",
            "isoprenoid (WYJ)",
            "jasmonate aid biosynthesis",
            "jasmonate aid biosynthesis(jlpeng)",
            "jasmonic acid biosynthesis",
            "jasmonic acid biosynthesis (v3.5)",
            "kaempferol glucoside biosynthesis (Arabidopsis)",
            "KDO transfer to lipid IV<SUB>A</SUB>",
            "lactose degradation",
            "lactose degradation 4",
            "leucine biosynthesis",
            "leucine biosynthesis (v4.0)",
            "leucine degradation",
            "leucine degradation (v4.0)",
            "leucine degradation I",
            "leucopelargonidin and leucocyanidin biosynthesis",
            "lignin biosynthesis",
            "lipases pathway",
            "lipid-A-precursor biosynthesis",
            "lipid-dependent phytate biosynthesis I (via Ins(1,4,5)P3)",
            "lipid-dependent phytate biosynthesis II (via Ins(1,3,4)P3)",
            "lipid-independent phytate biosynthesis",
            "lipoic acid biosynthesis-mt",
            "lupeol biosynthesis",
            "luteolin biosynthesis",
            "lysine biosynthesis",
            "lysine degradation I",
            "lysine degradation II",
            "lysine degradation III",
            "mannose degradation",
            "methionine biosynthesis",
            "methionine degradation (v3.5)",
            "methionine degradation II",
            "methionine salvage pathway",
            "methylerythritol phosphate pathway (v3.5)",
            "methylglyoxal degradation",
            "methylglyoxal degradation (v4.0)",
            "mevalonate degradation",
            "mevalonate pathway",
            "mevalonate pathway (v4.0)",
            "molybdenum cofactor biosynthesis",
            "monolignol glucosides biosynthesis",
            "monoterpene biosynthesis",
            "NAD biosynthesis (from aspartate) (v3.5)",
            "NAD biosynthesis I (from aspartate)",
            "NAD/NADH phosphorylation and dephosphorylation",
            "nitrate assimilation pathway",
            "non-oxidative branch of the pentose phosphate pathway",
            "non-oxidative branch of the pentose phosphate pathway (v4.0)",
            "NPR1",
            "oxidative branch of the pentose phosphate pathway",
            "oxidative branch of the pentose phosphate pathway (4.0)",
            "pantothenate biosynthesis",
            "phaseic acid biosynthesis",
            "PHB synthesis (transgenic arabidopsis)",
            "phenylalanine biosynthesis I",
            "phenylalanine biosynthesis II",
            "phenylpropanoid biosynthesis",
            "phenylpropanoid biosynthesis (v3.5)",
            "phenylpropanoid biosynthesis, initial reactions",
            "phospholipid biosynthesis",
            "phospholipid biosynthesis (v3.5)",
            "phospholipid desaturation pathway",
            "photorespiration",
            "photosynthesis",
            "photosynthesis (v4.0)",
            "photosynthesis, light reaction",
            "phylloquinone biosynthesis",
            "phytate degradation I",
            "phytate degradation II",
            "phytol salvage pathway",
            "phytyl-PP biosynthesis",
            "plastoquinone biosynthesis",
            "polyamine biosynthesis I",
            "polyamine biosynthesis III",
            "polyisoprenoid biosynthesis",
            "ppGpp biosynthesis",
            "proanthocyanidin biosynthesis from flavanols",
            "proline biosynthesis",
            "proline biosynthesis V (from arginine)",
            "proline degradation",
            "PRPP biosynthesis",
            "purine degradation",
            "purine nucleotide metabolism (phosphotransfer and nucleotide modification)",
            "purine nucleotide metabolism (phosphotransfer and nucleotide modification) (v4.0)",
            "putrescine biosynthesis",
            "putrescine biosynthesis by agmatinase",
            "putrescine biosynthesis via <i>N</i>-carbamoylputrescine",
            "pyridine nucleotide cycling (plants)",
            "pyridoxal 5'-phosphate salvage pathway",
            "pyridoxal 5'-phosphate salvage pathway (v4.0)",
            "pyrimidine nucleotide metabolism (phosphotransfer and nucleotide modification)",
            "pyrimidine salvage pathway",
            "quercetin glucoside biosynthesis (Arabidopsis)",
            "Regulation of ethylene signaling",
            "Regulation of Gibberellin metabolism",
            "removal of superoxide radicals",
            "ribitol utilization",
            "riboflavin and FMN and FAD biosynthesis",
            "ribose catabolism",
            "S-methylmethionine cycle",
            "SA-mediated plant disease resistance signal transduction",
            "salicylic acid biosynthesis",
            "salvage pathways of purine nucleosides",
            "SAM cycle",
            "serine biosynthesis",
            "serine-isocitrate lyase pathway",
            "side chain elongation cycle aliphatic glucosinolates (Arabidopsis)",
            "sinapate ester biosynthesis",
            "sinapoyl ester biosynthesis",
            "siroheme biosynthesis",
            "siroheme biosynthesis (v4.0)",
            "spermidine biosynthesis",
            "spermidine biosynthesis (v4.0)",
            "spermine biosynthesis",
            "spermine biosynthesis (v4.0)",
            "spermine biosynthesis II",
            "sphingolipid biosynthesis (plants)",
            "Spingolipid synthesis (WYJ)",
            "stachyose biosynthesis",
            "starch and cellulose biosynthesis",
            "starch biosynthesis",
            "starch degradation",
            "Starch degradation",
            "Starch synthesis",
            "sterol biosynthesis",
            "suberin biosynthesis",
            "sucrose biosynthesis",
            "sucrose biosynthesis (v4.0)",
            "sucrose degradation",
            "sucrose degradation (v4.0)",
            "sucrose degradation to ethanol and lactate (anaerobic)",
            "sulfate activation for sulfonation",
            "sulfite oxidation",
            "sulfolipid biosynthesis",
            "sulfur assimilation",
            "sulfur oxidation",
            "superpathway for gluconate utilization",
            "superpathway of acetyl-CoA biosynthesis",
            "superpathway of choline biosynthesis",
            "superpathway of citrulline metabolism",
            "superpathway of fatty acid biosynthesis",
            "superpathway of GA12 biosynthesis",
            "superpathway of gibberellin biosynthesis",
            "superpathway of glycolysis, pyruvate dehydrogenase, TCA, and glyoxylate bypass",
            "superpathway of glyoxylate cycle",
            "superpathway of histidine, purine and pyrimidine biosynthesis",
            "superpathway of isoleucine biosynthesis",
            "superpathway of KDO<SUB>2</SUB>-lipid A biosynthesis",
            "superpathway of lipid-dependent phytate biosynthesis",
            "superpathway of lysine, threonine, and methionine biosynthesis",
            "superpathway of oxidative and non-oxidative branches of pentose phosphate pathway",
            "superpathway of oxidative and non-oxidative branches of pentose phosphate pathway (v4.0)",
            "superpathway of pantothenate and coenzyme A biosynthesis",
            "superpathway of polyamine biosynthesis",
            "superpathway of proto- and siroheme biosynthesis",
            "superpathway of proto- and siroheme biosynthesis (v4.0)",
            "superpathway of ribose and deoxyribose phosphate degradation",
            "superpathway of sulfur amino acid biosynthesis",
            "TCA cycle",
            "tetrahydrofolate biosynthesis I",
            "thiamin biosynthesis",
            "thioredoxin pathway",
            "threonine biosynthesis from homoserine",
            "Thylakoid water-water cycle",
            "trans,trans-farnesyl diphosphate biosynthesis",
            "trehalose anabolism",
            "trehalose biosynthesis",
            "trehalose biosynthesis (v4.0)",
            "trehalose degradation (high osmolarity)",
            "trehalose pathway",
            "triacylglycerol biosynthesis",
            "triacylglycerol degradation",
            "tRNA charging pathway",
            "tryptophan biosynthesis",
            "tryptophan degradation",
            "tryptophan degradation III",
            "tyrosine biosynthesis I",
            "tyrosine biosynthesis II",
            "tyrosine degradation",
            "tyrosine degradation 1",
            "ubiquinone-9 biosynthesis",
            "UDP-D-apiose biosynthesis (from UDP-D-glucuronate)",
            "UDP-D-galacturonate biosynthesis I (from UDP-D-glucuronate)",
            "UDP-D-galacturonate biosynthesis II (from D-galacturonate)",
            "UDP-D-xylose biosynthesis",
            "UDP-galactose biosynthesis",
            "UDP-glucose biosynthesis (from glucose 6-phosphate)",
            "UDP-glucose biosynthesis (from sucrose)",
            "UDP-L-arabinose biosynthesis I (from UDP-xylose)",
            "UDP-L-arabinose biosynthesis II (from L-arabinose)",
            "UDP-L-rhamnose biosynthesis",
            "UDP-N-acetyl-D-glucosamine biosynthesis",
            "UDP-sugars interconversion",
            "urea cycle",
            "ureide biosynthesis",
            "ureide degradation",
            "valine biosynthesis",
            "valine biosynthesis (v4.0)",
            "valine degradation",
            "valine degradation (v4.0)",
            "very long chain fatty acid biosynthesis",
            "vitamin E biosynthesis",
            "volatile benzenoid ester biosynthesis",
            "xanthophyll cycle",
            "xylose degradation",
            "xylose degradation (v4.0)",
            "xylulose-monophosphate cycle"};

    public PathAndLocusSmasher() {
    }

    public static void main(String[] args) throws IOException {
        File infile = Utils.chooseFileToOpen();
        BufferedReader in = new BufferedReader(new FileReader(infile));
        TreeMap<PathData, String> mappy = new TreeMap();

        int line = 1;
        String thisLine;
        while ((thisLine = in.readLine()) != null) {
            String[] splitLine = thisLine.split("\t");
            if (splitLine.length != 5) {
                System.out.println("Whoa.  Line " + line + " has split length " + splitLine.length);
            }
            PathData key = new PathData(splitLine[0], splitLine[1], splitLine[2], splitLine[3]);
            Utils.appendMapEntry(mappy, key, splitLine[4], "\t");
            line++;
        }
        in.close();
        BufferedWriter out = new BufferedWriter(new FileWriter(new File(infile.getParent(), "pathlist.txt")));
        Set<PathData> i = mappy.keySet();
        ArrayList<String> remainingPaths = new ArrayList();
        for (String thisPath : allPaths) {
            remainingPaths.add(thisPath);
        }
        for (PathData thisKey : i) {
            String ids = mappy.get(thisKey);
            out.write(thisKey + "\t" + ids);
            out.newLine();
            remainingPaths.remove(thisKey.name);
        }


        System.out.println("Missing paths: ");
        for (String thisPath : remainingPaths) {
            System.out.println(thisPath);
        }
        out.close();
    }

    static class PathData implements Comparable<Object> {
        public String name;
        public String source;
        public String date;
        public String username;

        public PathData(String name, String source, String date, String username) {
            this.name = name;
            this.source = source;
            this.date = date;
            this.username = username;
        }

        @Override
		public String toString() {
            return name + "\t" + source + "\t" + username + "\t" + date;
        }

        @Override
		public int compareTo(Object o) {
            if ((o instanceof PathData)) {
                PathData data2 = (PathData) o;
                return name.compareTo(name);
            }
            return 1;
        }
    }
}
